### PR TITLE
Update dual list from DDF v2.4.7

### PR DESCRIPTION
**Pull request by boaz0**
image

//cc @nlcwong @rvsia @karelhala

### CODE REVIEW

**Comment by boaz0** [comment]
@nlcwong - can you answer this question?

//cc @rvsia

**Comment by nlcwong** [comment]
@boaz0 Let me check with the other apps in settings to see if it makes sense that our buttons match.

**Comment by boaz0** [comment]
@rvsia reverting the buttons labels change because Natalie needs more time to get answers from other teams.
If we need to update the buttons labels we will do it in a separate PR.

**Comment by boaz0** [comment]
Thanks a lot!

**Pull request merged**
